#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Fangs Blog

# Short bio or description (displayed in the header)
description: 一些技术心得

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: fduodev@gmail.com
  facebook:
  flickr:
  github: fdgogogo
  instagram: fdgogogo
  linkedin: jiaan-fang-b3164b42
  pinterest:
  rss: 1 # just type anything here for a working RSS icon
  twitter: fdgogogo
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: fdgogogo

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-36285944-2

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://fangs.work

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

tag_page_layout: tag_archive
tag_page_dir: tags
tag_permalink_style: pretty
tag_feed_layout: tag_feed
tag_feed_dir: tags

category_archive:
  path: blog
  slugify: true
monthly_archive:
  path: archives

#
# !! You don't need to change any of the configuration flags below !!
#

markdown: kramdown
highlighter: rouge
permalink: blog/:categories/:title/

# The release of Jekyll Now that you're using
version: v1.1.0

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-toc
  - jekyll/tagging
  - jekyll-tagging-related_posts

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME
    - nginx
    - docker-compose.yml
    - _docker
    - _utils
