
jekyll:
  image: jekyll/builder:pages
  user: root
  volumes:
    - .:/srv/jekyll
  command: jekyll build

nginx:
  image: nginx
  volumes:
    - ./_site:/usr/share/nginx/fangs.work:ro
    - ./_docker/nginx/certs:/certs:ro # 证书文件， 不在repo中
    - ./_docker/nginx/conf.d:/etc/nginx/conf.d:ro
  ports:
    - 80:80
    - 443:443
